### ISSUE TITLE
When listing slack channels, exclude the archived ones, we'll never bridge to them while archived.

### ISSUE THREAD

**Issue by pleasantone** [errror/hangupsbot#4]
Sorry this is a diff instead of a pull request, I've got branch/fork issues in my copy of slackrtm ATM, and
it's a one-liner that's obvious.

--- a/hangupsbot/plugins/slackrtm.py
+++ b/hangupsbot/plugins/slackrtm.py
@@ -366,7 +366,7 @@ class SlackRTM(object):

     def update_channelnames(self, channels=None):
         if channels is None:
-            response = json.loads(self.slack.api_call('channels.list').decode("utf-8"))
+            response = json.loads(self.slack.api_call('channels.list', exclude_archived=1).decode("utf-8"))
             channels = response['channels']
         channelnames = {}
         for c in channels:

**Comment by errror** [comment]
Wow, long time ago...
I think we resolved this in another way.
