### ISSUE TITLE
/bot slack_users command needed

### ISSUE THREAD

**Issue by pleasantone** [errror/hangupsbot#8]
Need way to get membership of slack channels to HO folks...

@errror any chance you want to do this?

See https://github.com/hangoutsbot/hangoutsbot/issues/440

**Comment by errror** [comment]
Well I just did, to see afterwards, that someone else was faster. ;-)

[slack_users.diff.txt](https://github.com/errror/hangupsbot/files/58190/slack_users.diff.txt)
